/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.jhk.gdh.serialization.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Foundation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1350480365813375865L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Foundation\",\"namespace\":\"org.jhk.gdh.serialization.avro\",\"fields\":[{\"name\":\"avatar\",\"type\":\"bytes\"},{\"name\":\"awards\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"creationTime\",\"type\":\"long\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"masterId\",\"type\":\"long\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"praises\",\"type\":\"int\"},{\"name\":\"titles\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.nio.ByteBuffer avatar;
  @Deprecated public java.util.List<java.lang.CharSequence> awards;
  @Deprecated public long creationTime;
  @Deprecated public java.lang.CharSequence description;
  @Deprecated public long id;
  @Deprecated public long masterId;
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public int praises;
  @Deprecated public java.util.List<java.lang.CharSequence> titles;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Foundation() {}

  /**
   * All-args constructor.
   */
  public Foundation(java.nio.ByteBuffer avatar, java.util.List<java.lang.CharSequence> awards, java.lang.Long creationTime, java.lang.CharSequence description, java.lang.Long id, java.lang.Long masterId, java.lang.CharSequence name, java.lang.Integer praises, java.util.List<java.lang.CharSequence> titles) {
    this.avatar = avatar;
    this.awards = awards;
    this.creationTime = creationTime;
    this.description = description;
    this.id = id;
    this.masterId = masterId;
    this.name = name;
    this.praises = praises;
    this.titles = titles;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return avatar;
    case 1: return awards;
    case 2: return creationTime;
    case 3: return description;
    case 4: return id;
    case 5: return masterId;
    case 6: return name;
    case 7: return praises;
    case 8: return titles;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: avatar = (java.nio.ByteBuffer)value$; break;
    case 1: awards = (java.util.List<java.lang.CharSequence>)value$; break;
    case 2: creationTime = (java.lang.Long)value$; break;
    case 3: description = (java.lang.CharSequence)value$; break;
    case 4: id = (java.lang.Long)value$; break;
    case 5: masterId = (java.lang.Long)value$; break;
    case 6: name = (java.lang.CharSequence)value$; break;
    case 7: praises = (java.lang.Integer)value$; break;
    case 8: titles = (java.util.List<java.lang.CharSequence>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'avatar' field.
   */
  public java.nio.ByteBuffer getAvatar() {
    return avatar;
  }

  /**
   * Sets the value of the 'avatar' field.
   * @param value the value to set.
   */
  public void setAvatar(java.nio.ByteBuffer value) {
    this.avatar = value;
  }

  /**
   * Gets the value of the 'awards' field.
   */
  public java.util.List<java.lang.CharSequence> getAwards() {
    return awards;
  }

  /**
   * Sets the value of the 'awards' field.
   * @param value the value to set.
   */
  public void setAwards(java.util.List<java.lang.CharSequence> value) {
    this.awards = value;
  }

  /**
   * Gets the value of the 'creationTime' field.
   */
  public java.lang.Long getCreationTime() {
    return creationTime;
  }

  /**
   * Sets the value of the 'creationTime' field.
   * @param value the value to set.
   */
  public void setCreationTime(java.lang.Long value) {
    this.creationTime = value;
  }

  /**
   * Gets the value of the 'description' field.
   */
  public java.lang.CharSequence getDescription() {
    return description;
  }

  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'masterId' field.
   */
  public java.lang.Long getMasterId() {
    return masterId;
  }

  /**
   * Sets the value of the 'masterId' field.
   * @param value the value to set.
   */
  public void setMasterId(java.lang.Long value) {
    this.masterId = value;
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'praises' field.
   */
  public java.lang.Integer getPraises() {
    return praises;
  }

  /**
   * Sets the value of the 'praises' field.
   * @param value the value to set.
   */
  public void setPraises(java.lang.Integer value) {
    this.praises = value;
  }

  /**
   * Gets the value of the 'titles' field.
   */
  public java.util.List<java.lang.CharSequence> getTitles() {
    return titles;
  }

  /**
   * Sets the value of the 'titles' field.
   * @param value the value to set.
   */
  public void setTitles(java.util.List<java.lang.CharSequence> value) {
    this.titles = value;
  }

  /**
   * Creates a new Foundation RecordBuilder.
   * @return A new Foundation RecordBuilder
   */
  public static org.jhk.gdh.serialization.avro.Foundation.Builder newBuilder() {
    return new org.jhk.gdh.serialization.avro.Foundation.Builder();
  }
  
  /**
   * Creates a new Foundation RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Foundation RecordBuilder
   */
  public static org.jhk.gdh.serialization.avro.Foundation.Builder newBuilder(org.jhk.gdh.serialization.avro.Foundation.Builder other) {
    return new org.jhk.gdh.serialization.avro.Foundation.Builder(other);
  }
  
  /**
   * Creates a new Foundation RecordBuilder by copying an existing Foundation instance.
   * @param other The existing instance to copy.
   * @return A new Foundation RecordBuilder
   */
  public static org.jhk.gdh.serialization.avro.Foundation.Builder newBuilder(org.jhk.gdh.serialization.avro.Foundation other) {
    return new org.jhk.gdh.serialization.avro.Foundation.Builder(other);
  }
  
  /**
   * RecordBuilder for Foundation instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Foundation>
    implements org.apache.avro.data.RecordBuilder<Foundation> {

    private java.nio.ByteBuffer avatar;
    private java.util.List<java.lang.CharSequence> awards;
    private long creationTime;
    private java.lang.CharSequence description;
    private long id;
    private long masterId;
    private java.lang.CharSequence name;
    private int praises;
    private java.util.List<java.lang.CharSequence> titles;

    /** Creates a new Builder */
    private Builder() {
      super(org.jhk.gdh.serialization.avro.Foundation.SCHEMA$);
    }
    
    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.jhk.gdh.serialization.avro.Foundation.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.avatar)) {
        this.avatar = data().deepCopy(fields()[0].schema(), other.avatar);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.awards)) {
        this.awards = data().deepCopy(fields()[1].schema(), other.awards);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.creationTime)) {
        this.creationTime = data().deepCopy(fields()[2].schema(), other.creationTime);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.description)) {
        this.description = data().deepCopy(fields()[3].schema(), other.description);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.id)) {
        this.id = data().deepCopy(fields()[4].schema(), other.id);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.masterId)) {
        this.masterId = data().deepCopy(fields()[5].schema(), other.masterId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.name)) {
        this.name = data().deepCopy(fields()[6].schema(), other.name);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.praises)) {
        this.praises = data().deepCopy(fields()[7].schema(), other.praises);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.titles)) {
        this.titles = data().deepCopy(fields()[8].schema(), other.titles);
        fieldSetFlags()[8] = true;
      }
    }
    
    /**
     * Creates a Builder by copying an existing Foundation instance
     * @param other The existing instance to copy.
     */
    private Builder(org.jhk.gdh.serialization.avro.Foundation other) {
            super(org.jhk.gdh.serialization.avro.Foundation.SCHEMA$);
      if (isValidValue(fields()[0], other.avatar)) {
        this.avatar = data().deepCopy(fields()[0].schema(), other.avatar);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.awards)) {
        this.awards = data().deepCopy(fields()[1].schema(), other.awards);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.creationTime)) {
        this.creationTime = data().deepCopy(fields()[2].schema(), other.creationTime);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.description)) {
        this.description = data().deepCopy(fields()[3].schema(), other.description);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.id)) {
        this.id = data().deepCopy(fields()[4].schema(), other.id);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.masterId)) {
        this.masterId = data().deepCopy(fields()[5].schema(), other.masterId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.name)) {
        this.name = data().deepCopy(fields()[6].schema(), other.name);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.praises)) {
        this.praises = data().deepCopy(fields()[7].schema(), other.praises);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.titles)) {
        this.titles = data().deepCopy(fields()[8].schema(), other.titles);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'avatar' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getAvatar() {
      return avatar;
    }

    /**
      * Sets the value of the 'avatar' field.
      * @param value The value of 'avatar'.
      * @return This builder.
      */
    public org.jhk.gdh.serialization.avro.Foundation.Builder setAvatar(java.nio.ByteBuffer value) {
      validate(fields()[0], value);
      this.avatar = value;
      fieldSetFlags()[0] = true;
      return this; 
    }

    /**
      * Checks whether the 'avatar' field has been set.
      * @return True if the 'avatar' field has been set, false otherwise.
      */
    public boolean hasAvatar() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'avatar' field.
      * @return This builder.
      */
    public org.jhk.gdh.serialization.avro.Foundation.Builder clearAvatar() {
      avatar = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'awards' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getAwards() {
      return awards;
    }

    /**
      * Sets the value of the 'awards' field.
      * @param value The value of 'awards'.
      * @return This builder.
      */
    public org.jhk.gdh.serialization.avro.Foundation.Builder setAwards(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[1], value);
      this.awards = value;
      fieldSetFlags()[1] = true;
      return this; 
    }

    /**
      * Checks whether the 'awards' field has been set.
      * @return True if the 'awards' field has been set, false otherwise.
      */
    public boolean hasAwards() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'awards' field.
      * @return This builder.
      */
    public org.jhk.gdh.serialization.avro.Foundation.Builder clearAwards() {
      awards = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'creationTime' field.
      * @return The value.
      */
    public java.lang.Long getCreationTime() {
      return creationTime;
    }

    /**
      * Sets the value of the 'creationTime' field.
      * @param value The value of 'creationTime'.
      * @return This builder.
      */
    public org.jhk.gdh.serialization.avro.Foundation.Builder setCreationTime(long value) {
      validate(fields()[2], value);
      this.creationTime = value;
      fieldSetFlags()[2] = true;
      return this; 
    }

    /**
      * Checks whether the 'creationTime' field has been set.
      * @return True if the 'creationTime' field has been set, false otherwise.
      */
    public boolean hasCreationTime() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'creationTime' field.
      * @return This builder.
      */
    public org.jhk.gdh.serialization.avro.Foundation.Builder clearCreationTime() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.CharSequence getDescription() {
      return description;
    }

    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public org.jhk.gdh.serialization.avro.Foundation.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.description = value;
      fieldSetFlags()[3] = true;
      return this; 
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public org.jhk.gdh.serialization.avro.Foundation.Builder clearDescription() {
      description = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Long getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public org.jhk.gdh.serialization.avro.Foundation.Builder setId(long value) {
      validate(fields()[4], value);
      this.id = value;
      fieldSetFlags()[4] = true;
      return this; 
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public org.jhk.gdh.serialization.avro.Foundation.Builder clearId() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'masterId' field.
      * @return The value.
      */
    public java.lang.Long getMasterId() {
      return masterId;
    }

    /**
      * Sets the value of the 'masterId' field.
      * @param value The value of 'masterId'.
      * @return This builder.
      */
    public org.jhk.gdh.serialization.avro.Foundation.Builder setMasterId(long value) {
      validate(fields()[5], value);
      this.masterId = value;
      fieldSetFlags()[5] = true;
      return this; 
    }

    /**
      * Checks whether the 'masterId' field has been set.
      * @return True if the 'masterId' field has been set, false otherwise.
      */
    public boolean hasMasterId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'masterId' field.
      * @return This builder.
      */
    public org.jhk.gdh.serialization.avro.Foundation.Builder clearMasterId() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public org.jhk.gdh.serialization.avro.Foundation.Builder setName(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.name = value;
      fieldSetFlags()[6] = true;
      return this; 
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public org.jhk.gdh.serialization.avro.Foundation.Builder clearName() {
      name = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'praises' field.
      * @return The value.
      */
    public java.lang.Integer getPraises() {
      return praises;
    }

    /**
      * Sets the value of the 'praises' field.
      * @param value The value of 'praises'.
      * @return This builder.
      */
    public org.jhk.gdh.serialization.avro.Foundation.Builder setPraises(int value) {
      validate(fields()[7], value);
      this.praises = value;
      fieldSetFlags()[7] = true;
      return this; 
    }

    /**
      * Checks whether the 'praises' field has been set.
      * @return True if the 'praises' field has been set, false otherwise.
      */
    public boolean hasPraises() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'praises' field.
      * @return This builder.
      */
    public org.jhk.gdh.serialization.avro.Foundation.Builder clearPraises() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'titles' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getTitles() {
      return titles;
    }

    /**
      * Sets the value of the 'titles' field.
      * @param value The value of 'titles'.
      * @return This builder.
      */
    public org.jhk.gdh.serialization.avro.Foundation.Builder setTitles(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[8], value);
      this.titles = value;
      fieldSetFlags()[8] = true;
      return this; 
    }

    /**
      * Checks whether the 'titles' field has been set.
      * @return True if the 'titles' field has been set, false otherwise.
      */
    public boolean hasTitles() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'titles' field.
      * @return This builder.
      */
    public org.jhk.gdh.serialization.avro.Foundation.Builder clearTitles() {
      titles = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    public Foundation build() {
      try {
        Foundation record = new Foundation();
        record.avatar = fieldSetFlags()[0] ? this.avatar : (java.nio.ByteBuffer) defaultValue(fields()[0]);
        record.awards = fieldSetFlags()[1] ? this.awards : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[1]);
        record.creationTime = fieldSetFlags()[2] ? this.creationTime : (java.lang.Long) defaultValue(fields()[2]);
        record.description = fieldSetFlags()[3] ? this.description : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.id = fieldSetFlags()[4] ? this.id : (java.lang.Long) defaultValue(fields()[4]);
        record.masterId = fieldSetFlags()[5] ? this.masterId : (java.lang.Long) defaultValue(fields()[5]);
        record.name = fieldSetFlags()[6] ? this.name : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.praises = fieldSetFlags()[7] ? this.praises : (java.lang.Integer) defaultValue(fields()[7]);
        record.titles = fieldSetFlags()[8] ? this.titles : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[8]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);  

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);  

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
