/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.jhk.interested.serialization.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ACTION { 
  CREATE, SUBSCRIBE, UNSUBSCRIBE, DELETE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ACTION\",\"namespace\":\"org.jhk.interested.serialization.avro\",\"symbols\":[\"CREATE\",\"SUBSCRIBE\",\"UNSUBSCRIBE\",\"DELETE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
