/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.jhk.interested.serialization.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class InterestId extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8788685879422992796L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"InterestId\",\"namespace\":\"org.jhk.interested.serialization.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public InterestId() {}

  /**
   * All-args constructor.
   */
  public InterestId(java.lang.Long id) {
    this.id = id;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Long value) {
    this.id = value;
  }

  /**
   * Creates a new InterestId RecordBuilder.
   * @return A new InterestId RecordBuilder
   */
  public static org.jhk.interested.serialization.avro.InterestId.Builder newBuilder() {
    return new org.jhk.interested.serialization.avro.InterestId.Builder();
  }
  
  /**
   * Creates a new InterestId RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new InterestId RecordBuilder
   */
  public static org.jhk.interested.serialization.avro.InterestId.Builder newBuilder(org.jhk.interested.serialization.avro.InterestId.Builder other) {
    return new org.jhk.interested.serialization.avro.InterestId.Builder(other);
  }
  
  /**
   * Creates a new InterestId RecordBuilder by copying an existing InterestId instance.
   * @param other The existing instance to copy.
   * @return A new InterestId RecordBuilder
   */
  public static org.jhk.interested.serialization.avro.InterestId.Builder newBuilder(org.jhk.interested.serialization.avro.InterestId other) {
    return new org.jhk.interested.serialization.avro.InterestId.Builder(other);
  }
  
  /**
   * RecordBuilder for InterestId instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<InterestId>
    implements org.apache.avro.data.RecordBuilder<InterestId> {

    private long id;

    /** Creates a new Builder */
    private Builder() {
      super(org.jhk.interested.serialization.avro.InterestId.SCHEMA$);
    }
    
    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.jhk.interested.serialization.avro.InterestId.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
    }
    
    /**
     * Creates a Builder by copying an existing InterestId instance
     * @param other The existing instance to copy.
     */
    private Builder(org.jhk.interested.serialization.avro.InterestId other) {
            super(org.jhk.interested.serialization.avro.InterestId.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Long getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public org.jhk.interested.serialization.avro.InterestId.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public org.jhk.interested.serialization.avro.InterestId.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public InterestId build() {
      try {
        InterestId record = new InterestId();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);  

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);  

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
