/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.jhk.interested.serialization.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class User extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7950020721857565098L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"User\",\"namespace\":\"org.jhk.interested.serialization.avro\",\"fields\":[{\"name\":\"picture\",\"type\":[\"null\",\"bytes\"],\"default\":null},{\"name\":\"address\",\"type\":{\"type\":\"record\",\"name\":\"Address\",\"fields\":[{\"name\":\"address\",\"type\":\"string\"},{\"name\":\"coordinates\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"double\"}],\"default\":null},{\"name\":\"description\",\"type\":\"string\"}]}},{\"name\":\"email\",\"type\":\"string\"},{\"name\":\"id\",\"type\":{\"type\":\"record\",\"name\":\"UserId\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"cookie\",\"type\":[\"null\",\"string\"],\"default\":null}]}},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"password\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.nio.ByteBuffer picture;
  @Deprecated public org.jhk.interested.serialization.avro.Address address;
  @Deprecated public java.lang.CharSequence email;
  @Deprecated public org.jhk.interested.serialization.avro.UserId id;
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.CharSequence password;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public User() {}

  /**
   * All-args constructor.
   */
  public User(java.nio.ByteBuffer picture, org.jhk.interested.serialization.avro.Address address, java.lang.CharSequence email, org.jhk.interested.serialization.avro.UserId id, java.lang.CharSequence name, java.lang.CharSequence password) {
    this.picture = picture;
    this.address = address;
    this.email = email;
    this.id = id;
    this.name = name;
    this.password = password;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return picture;
    case 1: return address;
    case 2: return email;
    case 3: return id;
    case 4: return name;
    case 5: return password;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: picture = (java.nio.ByteBuffer)value$; break;
    case 1: address = (org.jhk.interested.serialization.avro.Address)value$; break;
    case 2: email = (java.lang.CharSequence)value$; break;
    case 3: id = (org.jhk.interested.serialization.avro.UserId)value$; break;
    case 4: name = (java.lang.CharSequence)value$; break;
    case 5: password = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'picture' field.
   */
  public java.nio.ByteBuffer getPicture() {
    return picture;
  }

  /**
   * Sets the value of the 'picture' field.
   * @param value the value to set.
   */
  public void setPicture(java.nio.ByteBuffer value) {
    this.picture = value;
  }

  /**
   * Gets the value of the 'address' field.
   */
  public org.jhk.interested.serialization.avro.Address getAddress() {
    return address;
  }

  /**
   * Sets the value of the 'address' field.
   * @param value the value to set.
   */
  public void setAddress(org.jhk.interested.serialization.avro.Address value) {
    this.address = value;
  }

  /**
   * Gets the value of the 'email' field.
   */
  public java.lang.CharSequence getEmail() {
    return email;
  }

  /**
   * Sets the value of the 'email' field.
   * @param value the value to set.
   */
  public void setEmail(java.lang.CharSequence value) {
    this.email = value;
  }

  /**
   * Gets the value of the 'id' field.
   */
  public org.jhk.interested.serialization.avro.UserId getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(org.jhk.interested.serialization.avro.UserId value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'password' field.
   */
  public java.lang.CharSequence getPassword() {
    return password;
  }

  /**
   * Sets the value of the 'password' field.
   * @param value the value to set.
   */
  public void setPassword(java.lang.CharSequence value) {
    this.password = value;
  }

  /**
   * Creates a new User RecordBuilder.
   * @return A new User RecordBuilder
   */
  public static org.jhk.interested.serialization.avro.User.Builder newBuilder() {
    return new org.jhk.interested.serialization.avro.User.Builder();
  }
  
  /**
   * Creates a new User RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new User RecordBuilder
   */
  public static org.jhk.interested.serialization.avro.User.Builder newBuilder(org.jhk.interested.serialization.avro.User.Builder other) {
    return new org.jhk.interested.serialization.avro.User.Builder(other);
  }
  
  /**
   * Creates a new User RecordBuilder by copying an existing User instance.
   * @param other The existing instance to copy.
   * @return A new User RecordBuilder
   */
  public static org.jhk.interested.serialization.avro.User.Builder newBuilder(org.jhk.interested.serialization.avro.User other) {
    return new org.jhk.interested.serialization.avro.User.Builder(other);
  }
  
  /**
   * RecordBuilder for User instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<User>
    implements org.apache.avro.data.RecordBuilder<User> {

    private java.nio.ByteBuffer picture;
    private org.jhk.interested.serialization.avro.Address address;
    private org.jhk.interested.serialization.avro.Address.Builder addressBuilder;
    private java.lang.CharSequence email;
    private org.jhk.interested.serialization.avro.UserId id;
    private org.jhk.interested.serialization.avro.UserId.Builder idBuilder;
    private java.lang.CharSequence name;
    private java.lang.CharSequence password;

    /** Creates a new Builder */
    private Builder() {
      super(org.jhk.interested.serialization.avro.User.SCHEMA$);
    }
    
    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.jhk.interested.serialization.avro.User.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.picture)) {
        this.picture = data().deepCopy(fields()[0].schema(), other.picture);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.address)) {
        this.address = data().deepCopy(fields()[1].schema(), other.address);
        fieldSetFlags()[1] = true;
      }
      if (other.hasAddressBuilder()) {
        this.addressBuilder = org.jhk.interested.serialization.avro.Address.newBuilder(other.getAddressBuilder());
      }
      if (isValidValue(fields()[2], other.email)) {
        this.email = data().deepCopy(fields()[2].schema(), other.email);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.id)) {
        this.id = data().deepCopy(fields()[3].schema(), other.id);
        fieldSetFlags()[3] = true;
      }
      if (other.hasIdBuilder()) {
        this.idBuilder = org.jhk.interested.serialization.avro.UserId.newBuilder(other.getIdBuilder());
      }
      if (isValidValue(fields()[4], other.name)) {
        this.name = data().deepCopy(fields()[4].schema(), other.name);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.password)) {
        this.password = data().deepCopy(fields()[5].schema(), other.password);
        fieldSetFlags()[5] = true;
      }
    }
    
    /**
     * Creates a Builder by copying an existing User instance
     * @param other The existing instance to copy.
     */
    private Builder(org.jhk.interested.serialization.avro.User other) {
            super(org.jhk.interested.serialization.avro.User.SCHEMA$);
      if (isValidValue(fields()[0], other.picture)) {
        this.picture = data().deepCopy(fields()[0].schema(), other.picture);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.address)) {
        this.address = data().deepCopy(fields()[1].schema(), other.address);
        fieldSetFlags()[1] = true;
      }
      this.addressBuilder = null;
      if (isValidValue(fields()[2], other.email)) {
        this.email = data().deepCopy(fields()[2].schema(), other.email);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.id)) {
        this.id = data().deepCopy(fields()[3].schema(), other.id);
        fieldSetFlags()[3] = true;
      }
      this.idBuilder = null;
      if (isValidValue(fields()[4], other.name)) {
        this.name = data().deepCopy(fields()[4].schema(), other.name);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.password)) {
        this.password = data().deepCopy(fields()[5].schema(), other.password);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'picture' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getPicture() {
      return picture;
    }

    /**
      * Sets the value of the 'picture' field.
      * @param value The value of 'picture'.
      * @return This builder.
      */
    public org.jhk.interested.serialization.avro.User.Builder setPicture(java.nio.ByteBuffer value) {
      validate(fields()[0], value);
      this.picture = value;
      fieldSetFlags()[0] = true;
      return this; 
    }

    /**
      * Checks whether the 'picture' field has been set.
      * @return True if the 'picture' field has been set, false otherwise.
      */
    public boolean hasPicture() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'picture' field.
      * @return This builder.
      */
    public org.jhk.interested.serialization.avro.User.Builder clearPicture() {
      picture = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'address' field.
      * @return The value.
      */
    public org.jhk.interested.serialization.avro.Address getAddress() {
      return address;
    }

    /**
      * Sets the value of the 'address' field.
      * @param value The value of 'address'.
      * @return This builder.
      */
    public org.jhk.interested.serialization.avro.User.Builder setAddress(org.jhk.interested.serialization.avro.Address value) {
      validate(fields()[1], value);
      this.addressBuilder = null;
      this.address = value;
      fieldSetFlags()[1] = true;
      return this; 
    }

    /**
      * Checks whether the 'address' field has been set.
      * @return True if the 'address' field has been set, false otherwise.
      */
    public boolean hasAddress() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'address' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public org.jhk.interested.serialization.avro.Address.Builder getAddressBuilder() {
      if (addressBuilder == null) {
        if (hasAddress()) {
          setAddressBuilder(org.jhk.interested.serialization.avro.Address.newBuilder(address));
        } else {
          setAddressBuilder(org.jhk.interested.serialization.avro.Address.newBuilder());
        }
      }
      return addressBuilder;
    }

    /**
     * Sets the Builder instance for the 'address' field
     * @return This builder.
     */
    public org.jhk.interested.serialization.avro.User.Builder setAddressBuilder(org.jhk.interested.serialization.avro.Address.Builder value) {
      clearAddress();
      addressBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'address' field has an active Builder instance
     * @return True if the 'address' field has an active Builder instance
     */
    public boolean hasAddressBuilder() {
      return addressBuilder != null;
    }

    /**
      * Clears the value of the 'address' field.
      * @return This builder.
      */
    public org.jhk.interested.serialization.avro.User.Builder clearAddress() {
      address = null;
      addressBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'email' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmail() {
      return email;
    }

    /**
      * Sets the value of the 'email' field.
      * @param value The value of 'email'.
      * @return This builder.
      */
    public org.jhk.interested.serialization.avro.User.Builder setEmail(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.email = value;
      fieldSetFlags()[2] = true;
      return this; 
    }

    /**
      * Checks whether the 'email' field has been set.
      * @return True if the 'email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'email' field.
      * @return This builder.
      */
    public org.jhk.interested.serialization.avro.User.Builder clearEmail() {
      email = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public org.jhk.interested.serialization.avro.UserId getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public org.jhk.interested.serialization.avro.User.Builder setId(org.jhk.interested.serialization.avro.UserId value) {
      validate(fields()[3], value);
      this.idBuilder = null;
      this.id = value;
      fieldSetFlags()[3] = true;
      return this; 
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[3];
    }

    /**
     * Gets the Builder instance for the 'id' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public org.jhk.interested.serialization.avro.UserId.Builder getIdBuilder() {
      if (idBuilder == null) {
        if (hasId()) {
          setIdBuilder(org.jhk.interested.serialization.avro.UserId.newBuilder(id));
        } else {
          setIdBuilder(org.jhk.interested.serialization.avro.UserId.newBuilder());
        }
      }
      return idBuilder;
    }

    /**
     * Sets the Builder instance for the 'id' field
     * @return This builder.
     */
    public org.jhk.interested.serialization.avro.User.Builder setIdBuilder(org.jhk.interested.serialization.avro.UserId.Builder value) {
      clearId();
      idBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'id' field has an active Builder instance
     * @return True if the 'id' field has an active Builder instance
     */
    public boolean hasIdBuilder() {
      return idBuilder != null;
    }

    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public org.jhk.interested.serialization.avro.User.Builder clearId() {
      id = null;
      idBuilder = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public org.jhk.interested.serialization.avro.User.Builder setName(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.name = value;
      fieldSetFlags()[4] = true;
      return this; 
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public org.jhk.interested.serialization.avro.User.Builder clearName() {
      name = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'password' field.
      * @return The value.
      */
    public java.lang.CharSequence getPassword() {
      return password;
    }

    /**
      * Sets the value of the 'password' field.
      * @param value The value of 'password'.
      * @return This builder.
      */
    public org.jhk.interested.serialization.avro.User.Builder setPassword(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.password = value;
      fieldSetFlags()[5] = true;
      return this; 
    }

    /**
      * Checks whether the 'password' field has been set.
      * @return True if the 'password' field has been set, false otherwise.
      */
    public boolean hasPassword() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'password' field.
      * @return This builder.
      */
    public org.jhk.interested.serialization.avro.User.Builder clearPassword() {
      password = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    public User build() {
      try {
        User record = new User();
        record.picture = fieldSetFlags()[0] ? this.picture : (java.nio.ByteBuffer) defaultValue(fields()[0]);
        if (addressBuilder != null) {
          record.address = this.addressBuilder.build();
        } else {
          record.address = fieldSetFlags()[1] ? this.address : (org.jhk.interested.serialization.avro.Address) defaultValue(fields()[1]);
        }
        record.email = fieldSetFlags()[2] ? this.email : (java.lang.CharSequence) defaultValue(fields()[2]);
        if (idBuilder != null) {
          record.id = this.idBuilder.build();
        } else {
          record.id = fieldSetFlags()[3] ? this.id : (org.jhk.interested.serialization.avro.UserId) defaultValue(fields()[3]);
        }
        record.name = fieldSetFlags()[4] ? this.name : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.password = fieldSetFlags()[5] ? this.password : (java.lang.CharSequence) defaultValue(fields()[5]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);  

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);  

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
