/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.jhk.interested.serialization.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class UserId extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5780623706893648776L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserId\",\"namespace\":\"org.jhk.interested.serialization.avro\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"cookie\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.Long id;
  @Deprecated public java.lang.CharSequence cookie;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public UserId() {}

  /**
   * All-args constructor.
   */
  public UserId(java.lang.Long id, java.lang.CharSequence cookie) {
    this.id = id;
    this.cookie = cookie;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return cookie;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: cookie = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'cookie' field.
   */
  public java.lang.CharSequence getCookie() {
    return cookie;
  }

  /**
   * Sets the value of the 'cookie' field.
   * @param value the value to set.
   */
  public void setCookie(java.lang.CharSequence value) {
    this.cookie = value;
  }

  /**
   * Creates a new UserId RecordBuilder.
   * @return A new UserId RecordBuilder
   */
  public static org.jhk.interested.serialization.avro.UserId.Builder newBuilder() {
    return new org.jhk.interested.serialization.avro.UserId.Builder();
  }
  
  /**
   * Creates a new UserId RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserId RecordBuilder
   */
  public static org.jhk.interested.serialization.avro.UserId.Builder newBuilder(org.jhk.interested.serialization.avro.UserId.Builder other) {
    return new org.jhk.interested.serialization.avro.UserId.Builder(other);
  }
  
  /**
   * Creates a new UserId RecordBuilder by copying an existing UserId instance.
   * @param other The existing instance to copy.
   * @return A new UserId RecordBuilder
   */
  public static org.jhk.interested.serialization.avro.UserId.Builder newBuilder(org.jhk.interested.serialization.avro.UserId other) {
    return new org.jhk.interested.serialization.avro.UserId.Builder(other);
  }
  
  /**
   * RecordBuilder for UserId instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserId>
    implements org.apache.avro.data.RecordBuilder<UserId> {

    private java.lang.Long id;
    private java.lang.CharSequence cookie;

    /** Creates a new Builder */
    private Builder() {
      super(org.jhk.interested.serialization.avro.UserId.SCHEMA$);
    }
    
    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.jhk.interested.serialization.avro.UserId.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.cookie)) {
        this.cookie = data().deepCopy(fields()[1].schema(), other.cookie);
        fieldSetFlags()[1] = true;
      }
    }
    
    /**
     * Creates a Builder by copying an existing UserId instance
     * @param other The existing instance to copy.
     */
    private Builder(org.jhk.interested.serialization.avro.UserId other) {
            super(org.jhk.interested.serialization.avro.UserId.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.cookie)) {
        this.cookie = data().deepCopy(fields()[1].schema(), other.cookie);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Long getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public org.jhk.interested.serialization.avro.UserId.Builder setId(java.lang.Long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public org.jhk.interested.serialization.avro.UserId.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'cookie' field.
      * @return The value.
      */
    public java.lang.CharSequence getCookie() {
      return cookie;
    }

    /**
      * Sets the value of the 'cookie' field.
      * @param value The value of 'cookie'.
      * @return This builder.
      */
    public org.jhk.interested.serialization.avro.UserId.Builder setCookie(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.cookie = value;
      fieldSetFlags()[1] = true;
      return this; 
    }

    /**
      * Checks whether the 'cookie' field has been set.
      * @return True if the 'cookie' field has been set, false otherwise.
      */
    public boolean hasCookie() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'cookie' field.
      * @return This builder.
      */
    public org.jhk.interested.serialization.avro.UserId.Builder clearCookie() {
      cookie = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public UserId build() {
      try {
        UserId record = new UserId();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.cookie = fieldSetFlags()[1] ? this.cookie : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);  

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);  

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
